#!/usr/bin/env python3
"""Regenerates ios/Duit/Resources/PixelIconData.swift from the pixel icons in
the retro prototype (design/prototype/Main.dc.html, the `ICONS` object).

Each prototype icon is a 16x16 pixel-art SVG path made only of rectangles
("M7 1h2v1h-2z"). We convert them to plain (x, y, w, h) tuples so the Swift
side needs no path parsing. To use another icon, add its name to USED and
re-run:   python3 ios/Tools/gen_pixel_icons.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "design/prototype/Main.dc.html"
OUTPUT = ROOT / "ios/Duit/Resources/PixelIconData.swift"

USED = [
    # app chrome and tab bar
    "logo", "coin", "home", "activity", "plus", "chart", "panel",
    # window title icons
    "battery", "term", "hourglass", "cash", "search", "star", "briefcase",
    "check", "caution", "cloud", "arrowup",
    # wallets
    "bank", "phone", "card", "transfer",
    # category icons (see CategoryPixelIcon in Components/IconBadge.swift)
    "food", "coffee", "cart", "car", "building", "bulb", "tv", "bag",
    "cross", "book", "family", "gift", "plane", "box",
]

RECT = re.compile(r"M(\d+) (\d+)h(\d+)v(\d+)h-\d+z")


def load_icons() -> dict:
    for line in SOURCE.read_text().splitlines():
        m = re.match(r"const ICONS = (\{.*\});?\s*$", line)
        if m:
            return json.loads(m.group(1))
    raise SystemExit("ICONS object not found in " + str(SOURCE))


def rects(path: str) -> list:
    found = RECT.findall(path)
    if len(found) != path.count("M"):
        raise SystemExit("icon path has a segment that is not a plain rectangle")
    out = [tuple(int(n) for n in r) for r in found]
    for x, y, w, h in out:
        assert 0 <= x and 0 <= y and x + w <= 16 and y + h <= 16, (x, y, w, h)
    return out


def main() -> None:
    icons = load_icons()
    lines = [
        "// GENERATED by ios/Tools/gen_pixel_icons.py from design/prototype/Main.dc.html",
        "// (the prototype's `ICONS`). Do not edit by hand; edit USED in the script and re-run.",
        "//",
        "// Each icon is a list of filled rectangles (x, y, width, height) on a 16x16 grid.",
        "",
        "typealias PixelRects = [(x: Int, y: Int, w: Int, h: Int)]",
        "",
        "enum PixelIconData {",
    ]
    for name in USED:
        body = ", ".join("({},{},{},{})".format(*r) for r in rects(icons[name]))
        lines.append(f"    static let {name}: PixelRects = [{body}]")
    lines += ["", "    /// Every icon by name, for tests and lookups.", "    static let all: [String: PixelRects] = ["]
    lines += [f'        "{name}": {name},' for name in USED]
    lines += ["    ]", "}", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(USED)} icons)")


if __name__ == "__main__":
    main()
