import Foundation

/// The App Group the app and its widgets share. It must match the group in
/// the entitlements generated by project.yml. It's derived from the
/// placeholder bundle ID, so when the real bundle ID is chosen, change it in
/// both places (and in the Apple Developer portal).
enum AppGroup {
    static let identifier = "group.com.samidun26.duit"

    static var defaults: UserDefaults? { UserDefaults(suiteName: identifier) }
}

/// Where a widget tap should land inside the app. The URL scheme is
/// registered in project.yml (`CFBundleURLTypes`).
enum AppRoute: Equatable {
    /// Just open the app on Today.
    case today
    /// Open the app straight onto a new expense.
    case addExpense

    static let scheme = "duit"

    var url: URL {
        switch self {
        case .today: URL(string: "duit://today")!
        case .addExpense: URL(string: "duit://add")!
        }
    }

    init?(url: URL) {
        guard url.scheme == Self.scheme else { return nil }
        switch url.host {
        case "today": self = .today
        case "add": self = .addExpense
        default: return nil
        }
    }
}

/// The few numbers the widgets show. The app writes this (to the shared App
/// Group) whenever your data changes; widgets only read it. Keeping it this
/// small means the SwiftData store never has to move out of the app, and the
/// widget never touches your transactions.
struct WidgetSnapshot: Codable, Equatable {
    /// The calendar day these numbers were worked out for.
    var day: Date
    var spentToday: Int
    /// Expenses in `day`'s calendar month.
    var spentMonth: Int
    /// 0...1 of the spending money still left; nil until it's set.
    var batteryFraction: Double?
    /// Safe to spend per day until payday.
    var allowancePerDay: Int?
    var daysLeft: Int?
    /// True when the app lock is on: widgets then hide every amount.
    var hideAmounts: Bool
    /// "candy" | "arcade" | "sunset"
    var palette: String

    // MARK: Storage

    static let storageKey = "widget.snapshot.v1"

    static func load(from defaults: UserDefaults? = AppGroup.defaults) -> WidgetSnapshot? {
        guard let data = defaults?.data(forKey: storageKey) else { return nil }
        return try? JSONDecoder().decode(WidgetSnapshot.self, from: data)
    }

    func save(to defaults: UserDefaults? = AppGroup.defaults) {
        guard let defaults, let data = try? JSONEncoder().encode(self) else { return }
        defaults.set(data, forKey: Self.storageKey)
    }

    // MARK: Staleness
    // The app only rewrites the snapshot when it runs, so after midnight (or
    // a new month) a widget shows zero rather than yesterday's total.

    func spentToday(at now: Date, calendar: Calendar = .current) -> Int {
        calendar.isDate(day, inSameDayAs: now) ? spentToday : 0
    }

    func spentMonth(at now: Date, calendar: Calendar = .current) -> Int {
        calendar.isDate(day, equalTo: now, toGranularity: .month) ? spentMonth : 0
    }

    // MARK: Battery (same rules as Battery in the app)

    static let batteryCells = 20

    var batteryPercent: Int? { batteryFraction.map { Int(($0 * 100).rounded()) } }
    var batteryFilledCells: Int? { batteryFraction.map { Int(($0 * Double(Self.batteryCells)).rounded()) } }

    enum Level { case ok, warn, low }

    var level: Level {
        guard let f = batteryFraction else { return .ok }
        if f <= 0.2 { return .low }
        if f <= 0.5 { return .warn }
        return .ok
    }

    /// Made-up numbers for the widget gallery and placeholders.
    static let sample = WidgetSnapshot(
        day: Date(),
        spentToday: 45_000,
        spentMonth: 3_250_000,
        batteryFraction: 0.72,
        allowancePerDay: 68_357,
        daysLeft: 18,
        hideAmounts: false,
        palette: "candy"
    )
}
